version: 1
collection_name: open_drawer
root: /root/nas/piper_data/open_drawer
normalization_stats_path: /root/nas/piper_data/open_drawer/motus_shared/stats.json
datasets:
  - name: open_bottom_drawer
    path: open-bottom-drawer-trim
    weight: 1.0
    use_for_val: true
    excluded_episode_indices: [15]
    task_text: open the bottom drawer and put the stuff in the bottom drawer
  - name: open_top_drawer
    path: open-top-drawer-trim
    weight: 1.0
    excluded_episode_indices: [41]
    task_text: open the top drawer and put the stuff in the top drawer
